name: Pipeline PHP 7.3

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testsuite-php73:
    name: Testes Automatizados - PHP 7.3
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP 7.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências via Composer
        run: |
          composer install --no-progress -o --no-ansi --no-interaction

      - name: Rodar análises estáticas
        run: |
          composer stan

      - name: Rodar PHPUnit
        run: |
          composer test
